apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devcontainer
  name: devcontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devcontainer
  template:
    metadata:
      labels:
        app: devcontainer
    spec:
      serviceAccountName: admin
      hostPID: true
      containers:
      - image: ghcr.io/kylape/devcontainer:main
        imagePullPolicy: Always
        name: devcontainer
        resources: {}
        securityContext:
          privileged: true
        ports:
        - name: ssh
          containerPort: 22
        volumeMounts:
        - name: workspace
          mountPath: /root/workspace
        - name: sys-kernel-security
          mountPath: /sys/kernel/security
          readOnly: false
        - name: sys-kernel-debug
          mountPath: /sys/kernel/debug
          readOnly: false
        - name: bpffs
          mountPath: /sys/fs/bpf
          readOnly: false
        - name: podman-storage
          mountPath: /var/lib/containers
        - name: dev-fuse
          mountPath: /dev/fuse
        - name: podman-sock
          mountPath: /run/podman/podman.sock
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: devcontainer
      - name: sys-kernel-security
        hostPath:
          path: /sys/kernel/security
          type: Directory
      - name: sys-kernel-debug
        hostPath:
          path: /sys/kernel/debug
          type: Directory
      - name: bpffs
        hostPath:
          path: /sys/fs/bpf
          type: DirectoryOrCreate
      - name: podman-storage
        emptyDir: {}
      - name: dev-fuse
        hostPath:
          path: /dev/fuse
          type: CharDevice
      - name: podman-sock
        hostPath:
          path: /run/podman/podman.sock
          type: Socket
