apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devcontainer
  name: devcontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devcontainer
  template:
    metadata:
      labels:
        app: devcontainer
    spec:
      containers:
      - image: ghcr.io/kylape/devcontainer:main
        imagePullPolicy: Always
        name: devcontainer
        resources: {}
        ports:
        - name: ssh
          containerPort: 22
        volumeMounts:
        - name: src
          mountPath: /root/src
      volumes:
      - name: src
        persistentVolumeClaim:
          claimName: devcontainer
